sequence = "ATTTGGGACCTGGTGGAAAATACGATTGGTTTGAAAGTCAGCCGGTTGTTCTGAGGTACGCAAACGGAAAGTTTGAAGTGGGTTAACTTCATGTTCCGGACAAGCGAGTCCTAAAAGATAGACCTGGGGCGTCGCGATTTGGGGGCAAGCAAATGCATGTGTCACGAGACCGTGTGGCCCCCAATATGGGTCGGGGGCACGAGCTATAACTCCTCGGCTCACCTTTACAACACACATATGCGTGCACGTGCTGAAGCAGATGCACCACTGTTACCTGACTTGGGCGGCAGGCCTGGACAAATTGTAACCTAACCGGTATTCAGCCTCGCCACGTGGTAGACATCGATCTCTAGGCTGTGGGCAATGTTAACACGCATGTTTGACTGCTTCCTGCGCCAGGTGTCGGCTAGCAGAGGCTGCTTATCCGGATGTCCAAACGCCGACTTGGGACAGAGATCTGAATTACGTAGACGCGGCAACCAAAGTAGTCGGGCTAGTTGGTATCGGGGCAGGTATCTTAACTCGCGGCCGCCGCCCGCCCTTATACATCCATAAACCGCTCACGTTCCTCTTCATTGTCGGTATAGTGAAGATCAGTACCACTAAGGTGGTGAGGGCCCAGCTGGCTGGTCACATTAATCTAGACTAGGTCTCGATAGGCTACCTGTAGGGCTTACAGTGGCAAAACCCGTCGTCTAAATCACTAGCGACTCTGCATCATGGTTAGGAAGGTATATACCGTCTTGGCAAAATGGAAACTGGGCTCCAAAAGTCCGCCTTTGCAGCGGGCTGAGTCAGGTAGGGATTCTGACTTCCGAACCGGAATAACCCGTCGGGACTGTTAGCGCAGCATATACGGATTTTGAGCTCACGCTCTGGCCGGGCGACAGTGGGGAGATCCTCTATAGGCGTCTAAGTGTAAAGCGGATTAGGCTG"

n_A = 0
n_C = 0
n_G = 0
n_T = 0

for i in range(len(sequence)):
    match sequence[i]:
        case 'A':
            n_A += 1
        case 'C':
            n_C += 1
        case 'G':
            n_G += 1
        case 'T':
            n_T += 1

print(str(n_A), end=" ")
print(str(n_C), end=" ")
print(str(n_G), end=" ")
print(str(n_T), end=" ")