from io import StringIO


sequence = "ATATTGCCTGCGATCTTGTTTCGTCCCTTGACAAGCAACGTAGCCAAGCGTTAGGTGTAAGTCTGCCCCGGGCTCCCCCTCAGGATGCGCTATTGCAATGTTTTTGACGACTCCGGCTGGCATGCGGCCTTCGAACAAGGGCGTGATCAGGCAAGAGCAAGGTTAGCTACGCCTAGTTAAGCATTAGCGCTCCGGTATGAAAAACAATCTATAAAAGTTAACCCCGAGTAGGTCGCGTGCCTTTCACCTTATACCAAATCGCCTGTGCACTTCGTTCTGTGGCAACGACTTCCGAATGCCCAACATAGTCCGAATATCGAAGAGGTTAGTAGAGCTAGAGCCGGGTTGTAGGTGCGAAACGGACCAGTACCGTCTGGCTCTGTGCCAATGCCTGAATGTAGACCACATTTATTGGGCAGGGTCGCTGACAGACGTCGCGTTACAACTGTAAGCCCGGCCCAGGCACATTACAATCGTAAATTTACGTACTATACACTTTTGATATATTCGTTTATAGCCTCTTGCCATTGCCATAATACTTGCGATGTCTTTCCAGAGTTATGCCTGCGCGAAAGCCCTTGGATAGCGGGCATCGAATACGTAGCGTATTCGCAACCCGTGTCAAGTAGTCAAATCCTTCTGGAAAGCTACCGTCCAATTGGTCGTACGCTAGGCCTTACGGCGTTCGGAGGTGAGTTTGGGGGATCGTAACTACTAGGCTCCTTCGCGATCGCAGTTGAATCTTATACCCTAAGCATAACCGCGGCCGCAGCATTCAATTGCAATGGTGATGCGTGATTGTATTATAAGTATATACTGTCTAGTCAGGGTCGCTACCCCCAAGGATGGTAGGAAGGAAGGTTCCCGGTGGGGGCGCATGTAGTGGATCGAGATGCACTAACAAGGACTATGTAAGCTACCGCTCGATAGCCCTCAAGCTCACTTGTGAGTCAAGCGCGC"
reverse = ""
cStr = StringIO()

for n in sequence:
    match n:
        case 'A':
            cStr.write('T')
        case 'T':
            cStr.write('A')
        case 'G':
            cStr.write('C')
        case 'C':
            cStr.write('G')

reverse = cStr.getvalue()

restrictionSiteMap = []

for i in range(4, 13):
    for j in range(len(sequence) - i + 1):
        seqN = sequence[j : j + i]
        seqR = reverse[j : j + i]
        if seqN == seqR[::-1]:
            
            restrictionSiteMap.append(str(j + 1) + " " + str(i))

for restrictionSite in restrictionSiteMap:
    print(restrictionSite)