dataList = ["GCAGGATACCGAGGATACGGATCGCAGGATACAGGATACCCTAAGGATACCGCAGGATACAGGATACACTTACAGGATACTACGAGGATACCAGAAAAGGATACAGGATACCAGTAAGGATACTAGGATACCCTTACGGCTCAACAGGATACAGGATACAGGATACCCCAGGATACAGGATACGAGGATACAGGATACTTAGGATACAAGGATACCTTAGGATACAGAAAGGATACAACAGGATACAGAGGATACATCCGCCTGCAGCCCAAGAAGGATACCGAAACAAGGATACTAGGATACCTTTAAGGATACCGCCAAGGATACCAGGATACCAGGATACAGGATACAGGATACAGGATACCTAAACGAGGATACCAAGGATACAGGATACTGAGGATACAAGGATACAAAGGATACTCAGGATACGTAGGATACAGGATACGAGGATACCACAGGATACAGGATACCCAGGATACGAGGATACAGTTAGCAGGATACACAGGATACCAGGATACTGGGATTATTCAAGGATACCAGGATACTAAGGATACAAATCAGGATACCTGGTGGCGAGGATACAAGAGTCAGGATACAGAGGATACAGGATACGCAGGATACTAGGATACGCCCAGGATACCAGGATACAGGATACAGGATACTGCCGTCTAAGGATACCACAGGATACCAAGGATACTCAGGCGGAAGGATACAGGATACACCAGGATACCAGGATACCAAGGATACATAGGATACAGGATACGCACTAGGATACGGGCCCTACCTTCAAGGATACTGATACATAAAGGATACAGGATACAAAGGATACTTCAGGATACGAAGGATACAGGATACCTGCGCGGCAAGGATACATTCAGGATACAAGGATACAGGATACGTAGGATACCAAAGGATACAAAGGATACG"]
subStringList = ["AGGATACAG"]

for i in range(len(dataList)):
    count = 0
    subLen = len(subStringList[i])
    for j in range(len(dataList[i])):
        if dataList[i][j:j+subLen] == subStringList[i]:
            count = count + 1
    print("Data: " + dataList[i] + " ---- " + subStringList[i] + " ---- " + str(count))