import operator


data = "GATGGTGCTCGTCCCTAGTTGGATTTGCGTCCCTAGTTGGATTTGTGGCCGGTAGATGGTGCTTTGGATTTGGATGGTGCTCGTCCCTAGCTGACAACTGACAAGATGGTGCTCTGACAAGATGGTGCTTTGGATTTGTGGCCGGTAGATGGTGCTCTGACAATTGGATTTGGATGGTGCTTTGGATTTGTGGCCGGTATTGGATTTGTTGGATTTGTTGGATTTGCGTCCCTAGCGTCCCTAGCTGACAATGGCCGGTAGATGGTGCTCTGACAATGGCCGGTAGATGGTGCTGATGGTGCTCTGACAACTGACAATGGCCGGTACTGACAACGTCCCTAGCGTCCCTAGTGGCCGGTACGTCCCTAGTTGGATTTGCGTCCCTAGTGGCCGGTACGTCCCTAGGATGGTGCTCGTCCCTAGGATGGTGCTTGGCCGGTATTGGATTTGCGTCCCTAGCGTCCCTAGGATGGTGCTTTGGATTTGCGTCCCTAGCGTCCCTAGTGGCCGGTATGGCCGGTATGGCCGGTAGATGGTGCTCTGACAATGGCCGGTACGTCCCTAGGATGGTGCTCGTCCCTAGGATGGTGCTTGGCCGGTACTGACAATTGGATTTGTTGGATTTGGATGGTGCTCTGACAATTGGATTTGCTGACAATGGCCGGTACGTCCCTAGTGGCCGGTACTGACAATTGGATTTGGATGGTGCTTGGCCGGTACTGACAACTGACAAGATGGTGCTCGTCCCTAGCGTCCCTAGCTGACAACGTCCCTAGGATGGTGCTCTGACAAGATGGTGCTTGGCCGGTACGTCCCTAGCGTCCCTAGGATGGTGCTCGTCCCTAGCTGACAAGATGGTGCT"
k = 12

kmerDict = {}

# get unique k-mers in data string
for i in range(len(data)):
    if i == len(data) - k:
        break
    kmerDict[data[i:i+k]] = 0

for kmer in kmerDict.keys():
    count = 0

    for i in range(len(data)):
        if data[i:i+k] == kmer:
                count = count + 1
    
    kmerDict[kmer] = count

maxKey = max(kmerDict.items(), key=operator.itemgetter(1))[0]
maxVal = kmerDict[maxKey]

print(kmerDict)
print("Max: " + str(maxVal))

for kmer in kmerDict.keys():
     if kmerDict[kmer] == maxVal:
          print(kmer)
